CREATE TABLE `BLOG` (
  `BLOGID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(200) NOT NULL,
  `CONTENT` text,
  `FABUSHIJIAN` varchar(20) NOT NULL,
  `YUEDULIANG` int(11) DEFAULT NULL,
  `PEITU` varchar(200) DEFAULT NULL,
  `TAGS` varchar(20) DEFAULT NULL,
  `USERID` int(11) NOT NULL,
  PRIMARY KEY (`BLOGID`),
  KEY `USERID` (`USERID`),
  CONSTRAINT `blog_ibfk_1` FOREIGN KEY (`USERID`) REFERENCES `USER` (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `BLOGREPLY` (
  `REPLYID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTENT` varchar(2000) NOT NULL,
  `FABUSHIJIAN` varchar(20) NOT NULL,
  `REPLYUSERID` int(11) NOT NULL,
  `REPLYBLOGID` int(11) NOT NULL,
  `REPLYFORREPLYID` int(11) NOT NULL,
  PRIMARY KEY (`REPLYID`),
  KEY `REPLYBLOGID` (`REPLYBLOGID`),
  KEY `REPLYFORREPLYID` (`REPLYFORREPLYID`),
  KEY `REPLYUSERID` (`REPLYUSERID`),
  CONSTRAINT `blogreply_ibfk_1` FOREIGN KEY (`REPLYBLOGID`) REFERENCES `BLOG` (`BLOGID`),
  CONSTRAINT `blogreply_ibfk_2` FOREIGN KEY (`REPLYFORREPLYID`) REFERENCES `BLOGREPLY` (`REPLYID`),
  CONSTRAINT `blogreply_ibfk_3` FOREIGN KEY (`REPLYUSERID`) REFERENCES `USER` (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CAR` (
  `CARID` int(11) NOT NULL AUTO_INCREMENT,
  `PINPAIMING` varchar(20) NOT NULL,
  `XILIE` varchar(20) DEFAULT NULL,
  `SHOUJIA` float NOT NULL,
  `GOUMAISHIJIAN` varchar(20) NOT NULL,
  `GONGLISHU` int(11) NOT NULL,
  `PAILIANG` varchar(10) NOT NULL,
  `QICHESHOUTU` varchar(200) DEFAULT NULL,
  `MIAOSHU` text,
  `ZHUANGTAI` int(11) DEFAULT '0',
  `CHELIANGLEIXING` varchar(20) NOT NULL,
  `BIANSUXIANG` varchar(20) DEFAULT NULL,
  `DIJISHOU` int(11) DEFAULT NULL,
  `SHIPIN` varchar(200) DEFAULT NULL,
  `RANLIAOLEIXING` varchar(20) DEFAULT NULL,
  `SHIFOUTUIGUANG` bit(1) DEFAULT b'0',
  PRIMARY KEY (`CARID`)
) ENGINE=InnoDB   DEFAULT CHARSET=utf8;

CREATE TABLE `CARDETAIL` (
  `CARID` int(11) NOT NULL,
  `QUDONGLEIXING` varchar(20) DEFAULT NULL,
  `CHESHENYANSE` varchar(20) DEFAULT NULL,
  `QIGANGSHULIANG` varchar(0) DEFAULT NULL,
  `QIGANGBUJU` varchar(20) DEFAULT NULL,
  `ZUOWEISHULIANG` int(11) DEFAULT NULL,
  `XUANGUALEIXING` varchar(20) DEFAULT NULL,
  `QINANGSHULIANG` int(11) DEFAULT NULL,
  `YOUXIANGRONGJI` int(11) DEFAULT NULL,
  `CHESHENCHANGDU` int(11) DEFAULT NULL,
  `ZHOUJU` int(11) DEFAULT NULL,
  `LUNTAICHICUN` int(11) DEFAULT NULL,
  `HOUBEIXIANGRONGJI` int(11) DEFAULT NULL,
  `ZHUANXIANGFUZHU` varchar(20) DEFAULT NULL,
  `DAOCHELEIDA` bit(1) DEFAULT NULL,
  `LIDIJIANXI` int(11) DEFAULT NULL,
  `YOUHAO` float DEFAULT NULL,
  PRIMARY KEY (`CARID`),
  UNIQUE KEY `CARID` (`CARID`),
  CONSTRAINT `cardetail_ibfk_1` FOREIGN KEY (`CARID`) REFERENCES `CAR` (`CARID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CARIMAGE` (
  `IMAGEID` int(11) NOT NULL AUTO_INCREMENT,
  `CARID` int(11) DEFAULT NULL,
  `IMAGEPATH` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`IMAGEID`),
  KEY `CARID` (`CARID`),
  CONSTRAINT `carimage_ibfk_1` FOREIGN KEY (`CARID`) REFERENCES `CAR` (`CARID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE `CUSTOMER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `TEL` varchar(20) DEFAULT NULL,
  `LIUYAN` varchar(2000) DEFAULT NULL,
  `CARID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CARID` (`CARID`),
  CONSTRAINT `customer_ibfk_1` FOREIGN KEY (`CARID`) REFERENCES `CAR` (`CARID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `EMPLOYEE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `SEX` bit(1) DEFAULT NULL,
  `AGE` int(11) DEFAULT NULL,
  `IMAGE` varchar(200) DEFAULT NULL,
  `OFFICETEL` varchar(20) DEFAULT NULL,
  `MOBILE` varchar(20) DEFAULT NULL,
  `FAX` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `JOB` varchar(20) NOT NULL,
  `JIANJIE` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `KOWNLEGE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(200) NOT NULL,
  `CONTENT` text,
  `FABUSHIJIAN` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `NEW` (
  `NEWID` int(11) NOT NULL AUTO_INCREMENT,
  `BIAOTI` varchar(200) NOT NULL,
  `NEIRONG` text NOT NULL,
  `FABUSHIJIAN` varchar(20) NOT NULL,
  `FABUREN` varchar(20) DEFAULT NULL,
  `XINWENPEITU` varchar(200) DEFAULT NULL,
  `YUEDULIANG` int(11) DEFAULT NULL,
  `USERID` int(11) NOT NULL,
  PRIMARY KEY (`NEWID`),
  KEY `USERID` (`USERID`),
  CONSTRAINT `new_ibfk_1` FOREIGN KEY (`USERID`) REFERENCES `EMPLOYEE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `USER` (
  `USERID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(20) NOT NULL,
  `PASSWORD` varchar(200) NOT NULL,
  `NICKNAME` varchar(20) NOT NULL,
  `SEX` bit(1) DEFAULT NULL,
  `AGE` int(11) DEFAULT NULL,
  `IMAGE` varchar(200) DEFAULT NULL,
  `JOB` varchar(20) DEFAULT NULL,
  `JIALING` int(11) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `TEL` varchar(20) DEFAULT NULL,
  `JIANJIE` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
